### ISSUE TITLE
unlinked characterization factors with biosphere from ecoinvent 3.8 

### ISSUE THREAD

**Issue by dsavelief** [brightway-lca/brightway2-io#113]
Hello,

thanks Chris for updating the biosphere elementary flows to ecoinvent 3.8 !
Unfortunately the updated file [ecoinvent elementary flows 3.8.xml](https://github.com/brightway-lca/brightway2-io/blob/ca664d019d251a9e08cc79ff51fa82fb376d1383/bw2io/data/lci/ecoinvent%20elementary%20flows%203.8.xml) does not match anymore with  [LCIA_implementation_3.6.xlsx](https://github.com/brightway-lca/brightway2-io/blob/ca664d019d251a9e08cc79ff51fa82fb376d1383/bw2io/data/lcia/LCIA_implementation_3.6.xlsx) and some unlinked characterization factors are found:

```
ei = bw2io.importers.EcoinventLCIAImporter()
ei.apply_strategies()
ei.statistics()
```
returns
> 850 methods
> 219059 cfs
> 465 unlinked cfs
> (850, 219059, 465)

```
[(exc["name"], exc["categories"]) for exc in ei.unlinked]`
```
returns 7 unlinked exchanges :
> [('Tri-allate', ('soil', 'agricultural')),
>  ('Carfentrazone ethyl ester', ('soil', 'agricultural')),
>  ('Chlorotoluron', ('soil', 'agricultural')),
>  ('Cyfluthrin', ('soil', 'agricultural')),
>  ('Thiophanat-methyl', ('soil', 'agricultural')),
>  ('Cyfluthrin', ('air', 'non-urban air or from high stacks')),
>  ('Flurochloridone', ('soil', 'agricultural'))]

These elementary flows have been removed from [ecoinvent elementary flows 3.8.xml](https://github.com/brightway-lca/brightway2-io/blob/ca664d019d251a9e08cc79ff51fa82fb376d1383/bw2io/data/lci/ecoinvent%20elementary%20flows%203.8.xml) I guess it is because they are no longer referenced by any ecoinvent 3.8 activity.

There is a method called add_missing_cfs but I didn't figure how to make it work (or exactly it creates exactly one elementary flow per characterization factor, in this case 465 new flows instead of 7):
https://github.com/brightway-lca/brightway2-io/blob/ca664d019d251a9e08cc79ff51fa82fb376d1383/bw2io/importers/base_lcia.py#L110 

Is it a good idea to fix the add_missing_cfs  method and add it to the default strategies of [bw2io/importers/ecoinvent_lcia.py](https://github.com/brightway-lca/brightway2-io/blob/ca664d019d251a9e08cc79ff51fa82fb376d1383/bw2io/importers/ecoinvent_lcia.py) ?

**Comment by StpdFox** [comment]
So i'm experiencing a similar problem with the unlinked exchanges. 

When i create a new project as follows, 
`bd.projects.set_current("new_test_project")
bw.bw2setup()
print(bd.methods.list)`

The biosphere3 database does get created but i run into an error with the LCIA methods 
`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/vosm4/PycharmProjects/Bw2setup_Test/main.py", line 8, in <module>
    bw.bw2setup()
  File "/Users/vosm4/opt/anaconda3/envs/ab_dev_3.6.4a/lib/python3.8/site-packages/bw2io/__init__.py", line 120, in bw2setup
    create_default_lcia_methods()
  File "/Users/vosm4/opt/anaconda3/envs/ab_dev_3.6.4a/lib/python3.8/site-packages/bw2io/__init__.py", line 110, in create_default_lcia_methods
    ei.write_methods(overwrite=overwrite)
  File "/Users/vosm4/opt/anaconda3/envs/ab_dev_3.6.4a/lib/python3.8/site-packages/bw2io/importers/base_lcia.py", line 53, in write_methods
    raise ValueError(
ValueError: Can't write unlinked methods (465 unlinked cfs)`

Resulting in an emtpy method lists, 

`Unfortunately the updated file ecoinvent elementary flows 3.8.xml does not match anymore with LCIA_implementation_3.6.xlsx and some unlinked characterization factors are found:`

In my bw2io the ecoinvent elementary flows. 3.8.xml only contains a row with 
`
/@majorRelease | /@majorRevision | /@minorRelease | /@minorRevision
` etc.....

This is all quite new to me but i would like to learn what the issue is here

**Comment by dsavelief** [comment]
Hi,

it seems we have exactly the same issue, we certainly have the same 465 unlinked cfs !
Your xml file should contain much more than a single row, it has been processed by bw2setup to create the biosphere3 flows.

In this file there are some elementary flows whose name has been prefixed with [Deleted], for instance:
> [Deleted]Tri-allate
> [Deleted]Carfentrazone ethyl ester
> [Deleted]Fluorochloridone

I see 3 alternative short-term fixes to avoid this issue : 
1.  use the old xml file for ecoinvent 3.7 but flows will be unlinked when importing ecoinvent 3.8
2. modify the LCIA_implementation_3.6.xlsx to remove the characterization factors not yet in ecoinvent 3.8 but calculations done with ecoinvent 3.7 may be erroneous
3. modify the xml file for ecoinvent 3.8 with the 7 elementary referenced in the first message

A more long-term resolution would be to ensure that if a lcia method contains a characterization factor for a flow not found in biosphere, it is automatically created. It seems doable and a method seems to exist for this, but I am not sure I have a complete understanding of the issue and would like to hear from others before I run into trouble ...

**Comment by cmutel** [comment]
@dsavelief @StpdFox Could I get an update on this issue? We now use the 3.8 LCIA and 3.8 biosphere flow lists, in [all their glory](https://github.com/brightway-lca/brightway2-io/blob/master/bw2io/strategies/lcia.py#L129). This applies cleanly.

As far as I can tell, there would now be an issue if you wanted to apply the 3.6 LCIA implementation against 3.8, but I am not sure this is worth worrying about... ?

Sorry about only responding now, I am not getting notified on issues unless explicitly tagged and so have missed a lot of feedback.

**Comment by StpdFox** [comment]
This issue is actually fixed with the updates. We aren't having any problems with this anymore

**Comment by dsavelief** [comment]
The 3.8 LCIA implementation update has resolved the issue for us also, I can close this issue !
