### ISSUE TITLE
FileNotFoundError in migrated project to bw2.5

### ISSUE THREAD

**Issue by mfastudillo** [brightway-lca/brightway2-io#115]
Hi all 

This error may be a bit tricky to replicate, but I have tried to migrate a project from bw2 to bw2.5 and when creating a database from an excel file I got a `FileNotFoundError`

I was running

```python
ei = ExcelImporter(path_exemple_excel)
ei.apply_strategies()
```
I tried to do the migration again, but this throws an `AssertionError` as the migration was already done

![imagen](https://user-images.githubusercontent.com/11621547/137169710-3456abde-eeaa-4953-baba-a7d3da1e68f9.png)

If I create a project from scratch and run the same code I don't find this `FileNotFound` error. 

For the moment I'll probably restart the whole project from scratch, but I thought it was worth noting this potential problem.

@cmutel

**Comment by cmutel** [comment]
@mfastudillo Thanks a lot for this error report.

I changed the algorithm that creates the hash string in the filename, to make it shorter because it was causing problems on Windows (which has limits on filepath lengths). So in bw2:

```python

>>> bi.Migration("biosphere-2-3-categories").filename
'biosphere-2-3-categories.c4c23e4d830d2b633703f1a65f9cdd0f'
```

While on bw25:

```python

>>> bi.Migration("biosphere-2-3-categories").filename
'biosphere-2-3-categories.c4c23e4d'
```

The way to fix this is to change the filenames when switching to 2.5, this should be more or less OK, but will take a bit of time.

**Comment by cmutel** [comment]
Fixed in https://github.com/brightway-lca/brightway2-data/commit/d317107f7e2fd5b57a6ba5337d22c98ac617b6f6
