### ISSUE TITLE
KeyError in IOTable backend

### ISSUE THREAD

**Issue by mfastudillo** [brightway-lca/brightway2-io#255]
I've been using the IOTable backend and the calculations work fine, but there seems to be a problem when trying to iterate over the exchanges. I am not sure of what the cause of the problem is. @michaelweinold or perhaps @BenPortner know ? 

![imagen](https://github.com/brightway-lca/brightway2-io/assets/11621547/9df67e72-2d85-4ea6-8ee3-c18e1b4f0630)

**Comment by BenPortner** [comment]
This code is part of a re-write that @cmutel did so I'm not 100% sure. It seems to me that https://github.com/brightway-lca/brightway2-data/commit/f3a3db2534f8ce73552bc75eb5be094afa8e56b7 fixed a similar error for the technosphere flows. @mfastudillo since you already have it all set up: Could you check if changing line 231 to 

```python
bm = lambda x: any(obj.get("matrix") == "biosphere_matrix" for obj in x.values())
```

Solves the problem?

**Comment by mfastudillo** [comment]
it seems to be as easy as that @BenPortner :)

**Comment by BenPortner** [comment]
Fixed in https://github.com/brightway-lca/brightway2-data/commit/dad31e5f934707f83109290073c2982e9ca664b1
