### ISSUE TITLE
bw2io exporter to excel doesn't find the correct reference product name

### ISSUE THREAD

**Issue by KarinTreyer** [brightway-lca/brightway2-io#69]
When exporting LCI with the bw2io exporter, the result in excel doesn't have the correct reference product, which leads to issues in the matrix calculation.
Example in the screenshot. A) is the original import of the LCI to BW2, and B) is the resulting LCI exported from BW2 with the reference product name which is the activity name instead of the correct reference product name.
![image](https://user-images.githubusercontent.com/28534018/85023743-6f035200-b175-11ea-8b1f-31db70727a1b.png)
![image](https://user-images.githubusercontent.com/28534018/85023842-8c382080-b175-11ea-99f1-17f3652e91ba.png)

**Comment by BenPortner** [comment]
This can be fixed by a change in bw2io/strategies/generic.py function `assign_only_product_as_production` line 90:

current version:
```python
ds['reference product'] = product['name']
```

new version:
```python
ds['reference product'] = product.get('reference product',[]) or product['name']
```

However, I cannot push this right now because I am not sure that it will not break anything. When running `pytest` on bw2io I get 6 errors, which I need to look into first.
