### ISSUE TITLE
mixed data types in elementary flow categories in biosphere3

### ISSUE THREAD

**Issue by mfastudillo** [brightway-lca/brightway2-io#85]
usually the categories of elementary flows are a tuple. but if I run `[f for f in bw.Database('biosphere3') if isinstance(f['categories'],list)]` in a newly created project I get 3 flows whose categories are a list. (bw2io version 7.12.1)

- 'residual softwood, wet' (cubic meter, None, ['social']
- 'Carbon dioxide, non-fossil, from calcination' (kilogram, None, ['air'])
-  'residual hardwood, wet' (cubic meter, None, ['social'])

I am not sure why, but it would be better to have just one data type.

**Comment by cmutel** [comment]
It is because these flows were used in previous versions of ecoinvent, but were later no longer used, and so aren't present in the master flow list. We [include them for backwards compatibility](https://github.com/brightway-lca/brightway2-io/blob/master/bw2io/importers/ecospold2_biosphere.py#L47), but [as a JSON file](https://github.com/brightway-lca/brightway2-io/blob/master/bw2io/data/lci/previous%20elementary%20flows.json); however, JSON does not have tuples, only lists, so the categories weren't imported correctly.
